Repository AY2122S1-CS2103T-T12-4/tp, pull requests merged in 2021-10, with the labels that each got.

#40 Update AboutUs.md
  docs/AboutUs.md
Labels: documentation

#74 remove parameter counter from tuition class
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/RemarkClassCommand.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tuition/Counter.java
  src/main/java/seedu/address/model/tuition/TuitionClass.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTuition.java
Labels: enhancement

#76 update addclass UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
Labels: documentation

#80 Sort tuition class
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddToClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tuition/Timeslot.java
  src/main/java/seedu/address/model/tuition/UniqueTuitionList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#106 Update Userguide.md for Timetable Command
  docs/UserGuide.md
Labels: documentation

#111 Implement input history navigation and command shortcuts
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddToClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditClassCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindClassCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListClassCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemarkClassCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveStudentCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/ViewClassCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewTodayTuitionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tuition/TuitionClass.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/InputHistory.java
  src/main/java/seedu/address/ui/infopage/TodayTuitionClassInfoPage.java
  src/main/java/seedu/address/ui/infopage/TuitionClassInfoPage.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/TuitionClassInfoPage.fxml
  src/test/java/seedu/address/model/InputHistoryTest.java
Labels: enhancement

#112 Update Developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TimetableCommand.java
  src/main/java/seedu/address/model/tuition/Timetable.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/infopage/TimetableInfoPage.java
  src/main/resources/view/TimetableInfoPage.fxml
Labels: documentation

#113 Ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RemarkCommandSequenceDiagram.puml
  docs/images/RemarkCommandSequenceDiagram.png
  docs/images/Ui.png
  docs/images/helpWindow.png
  docs/images/remarkEditor.png
  src/main/java/seedu/address/logic/commands/RemarkClassCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/ui/CommandFormat.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: documentation

#177 Fix minor formatting issues
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug, documentation

#186 Fix AddCommand adding same student
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: bug

#188 Ped issues 1.2
  docs/UserGuide.md
  docs/images/helpWindow.png
  src/main/java/seedu/address/commons/core/Browser.java
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddToClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkClassCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveStudentCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/TimetableCommand.java
  src/main/java/seedu/address/model/tuition/ClassLimit.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/infopage/StudentInfoPage.java
  src/main/java/seedu/address/ui/infopage/TuitionClassInfoPage.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/StudentInfoPage.fxml
  src/main/resources/view/TuitionClassInfoPage.fxml
Labels: documentation
